eis:
  container_name: eis
  image: ogut/eis:0.0.1
  links:
    - mysql
  env_file:
    - common.env
    - eis.env
  actions:
    - create_databases:
      - eis.env
    - create_oidcclients:
      - eis.env


eisfrontend:
    container_name: eisfrontend
    image: ogut/eis-frontend:0.0.1
    env_file:
        - common.env
        - eis.env
